### ISSUE TITLE
The dyed backpacks able to place floor

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/DyedBackpacks#5]
## Description (Required)

The dyed backpacks able to place. The ID lost when break.
## Steps to reproduce the Issue (Required)

1. Place dyed backpack to floor.
2. Break dyed backpack.
3. Lost ID.

<img width="434" alt="Annotation 2020-01-29 165414" src="https://user-images.githubusercontent.com/8324198/73374218-23313880-42ba-11ea-90af-649b2a750970.png">
<img width="830" alt="Annotation 2020-01-29 171059" src="https://user-images.githubusercontent.com/8324198/73374376-5c69a880-42ba-11ea-9bdb-63bad760c8d5.png">
<img width="322" alt="Annotation 2020-01-29 17d0701" src="https://user-images.githubusercontent.com/8324198/73374240-2f1cfa80-42ba-11ea-8fa5-6b588802a3b9.png">

## Expected behavior (Required)

The dyed backpacks no able to place floor

## Environment (Required)

 - Minecraft Version: 1.15.2
 - CS-CoreLib Version: vDEV - 80 (git e3242c60)
 - Slimefun Version: vDEV - 416 (git b94e197f)
 - Plugin Version: DyedBackpacks vDEV - 1 (git 4b4d1f0f)

**Comment by TheBusyBiscuit** [comment]
Fixed in the next Slimefun build.
